name: Deploy to Github Pages

on:
  push:
    branches:
      - "main"
    paths-ignore:
      - "**/*.[mM][dD]"
  workflow_dispatch:
    inputs:
      tags:
        description: "Environment variables reloading"

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Deploy Vue
        uses: Daniele-Tentoni/VuePagesAction@v1.0.5
        with:
          username: "Daniele-Tentoni"
          reponame: "docker-exp"
          token: ${{ secrets.PAGES_TOKEN }}
          branch: "master"

  push-to-registry:
    env:
      PUBLIC_PATH: "/"
      VUE_APP_MESSAGE: "Welcome to GITHUB ACTIONS Vue.js App"
      IMAGE_NAME: docker-exp

    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: antonioparolisi/${{ env.IMAGE_NAME }}
          tags: |
            type=schedule
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha

      - name: get-npm-version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@master

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags:
            antonioparolisi/${{ env.IMAGE_NAME }}:${{ steps.package-version.outputs.current-version }},
            antonioparolisi/${{ env.IMAGE_NAME }}:latest
          labels: ${{ steps.meta.outputs.labels }}
